openapi: 3.0.0
info:
  title: OTP Authentication API
  description: API de gestion des codes OTP pour l'authentification des citoyens
  version: 1.0.0

paths:
  /v1/auth/otp/request:
    post:
      tags:
        - OTP
      summary: Demande d'envoi d'un code OTP par SMS
      description: |
        Génère et envoie un code de vérification OTP (One-Time Password) par SMS au numéro de téléphone fourni.
        
        **Comportement :**
        - Génère un code à 6 chiffres valable 5 minutes
        - Invalide automatiquement les anciens codes OTP pour ce numéro
        - Envoie le code via le service SMS Letexto
        - Conserve l'historique des codes pour audit

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phoneNumber
              properties:
                phoneNumber:
                  type: string
                  pattern: '^[0-9]{8,10}$'
                  description: Numéro de téléphone (8 à 10 chiffres)
                  example: "01234567"

      responses:
        '200':
          description: Code OTP envoyé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Code de vérification envoyé par SMS"
                  data:
                    type: object
                    properties:
                      phoneNumber:
                        type: string
                        example: "01234567"
                      expiresIn:
                        type: string
                        example: "5 minutes"

        '400':
          description: Erreur de requête
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    oneOf:
                      - type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                              example: "field"
                            value:
                              type: string
                            msg:
                              type: string
                            path:
                              type: string
                            location:
                              type: string
                      - type: object
                        properties:
                          missingFields:
                            type: array
                            items:
                              type: string
                          message:
                            type: string
              examples:
                missingFields:
                  summary: Champ phoneNumber manquant
                  value:
                    message: "Champs manquants"
                    data:
                      missingFields: ["phoneNumber"]
                      message: "Les champs suivants sont obligatoires: phoneNumber"
                invalidPhoneFormat:
                  summary: Format de numéro invalide
                  value:
                    message: "Numéro de téléphone invalide"
                    data: null
                unauthorizedFields:
                  summary: Champs non autorisés
                  value:
                    message: "Champs non autorisés"
                    data:
                      unauthorizedFields: ["extraField"]
                      allowedFields: ["phoneNumber"]
                      message: "Les champs suivants ne sont pas autorisés: extraField"

        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    nullable: true
              examples:
                smsError:
                  summary: Erreur lors de l'envoi du SMS
                  value:
                    message: "Erreur lors de l'envoi du SMS"
                    data: null
                internalError:
                  summary: Erreur interne du serveur
                  value:
                    message: "Erreur interne du serveur"
                    data: null

      security: []

  /v1/auth/otp/verify:
    post:
      tags:
        - OTP
      summary: Vérification d'un code OTP
      description: |
        Vérifie la validité d'un code OTP pour un numéro de téléphone donné.
        
        **Sécurité renforcée :**
        - Vérifie que le code n'a pas déjà été utilisé
        - Vérifie la validité temporelle (expiration)
        - Marque automatiquement le code comme utilisé après validation
        - Empêche la réutilisation des codes validés
        
        **Note :** Cette route ne crée pas de compte utilisateur, elle ne fait que valider l'OTP.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phoneNumber
                - otp
              properties:
                phoneNumber:
                  type: string
                  pattern: '^[0-9]{8,10}$'
                  description: Numéro de téléphone (même que pour la demande OTP)
                  example: "01234567"
                otp:
                  type: string
                  pattern: '^[0-9]{6}$'
                  description: Code OTP à 6 chiffres reçu par SMS
                  example: "123456"

      responses:
        '200':
          description: Code OTP validé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Code de vérification validé avec succès"
                  data:
                    type: object
                    properties:
                      phoneNumber:
                        type: string
                        example: "01234567"
                      validated:
                        type: boolean
                        example: true

        '400':
          description: Erreur de validation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    oneOf:
                      - type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            value:
                              type: string
                            msg:
                              type: string
                            path:
                              type: string
                            location:
                              type: string
                      - type: object
                        nullable: true
              examples:
                missingFields:
                  summary: Champs requis manquants
                  value:
                    message: "Champs manquants"
                    data:
                      missingFields: ["phoneNumber", "otp"]
                      message: "Les champs suivants sont obligatoires: phoneNumber, otp"
                alreadyUsed:
                  summary: Code OTP déjà utilisé
                  value:
                    message: "Ce code a déjà été utilisé. Demandez un nouveau code de vérification."
                    data: null
                notFound:
                  summary: Code OTP introuvable
                  value:
                    message: "Code de vérification introuvable. Demandez un nouveau code."
                    data: null
                expired:
                  summary: Code OTP expiré
                  value:
                    message: "Code de vérification expiré. Demandez un nouveau code."
                    data: null
                incorrect:
                  summary: Code OTP incorrect
                  value:
                    message: "Code de vérification incorrect"
                    data: null
                unauthorizedFields:
                  summary: Champs non autorisés
                  value:
                    message: "Champs non autorisés"
                    data:
                      unauthorizedFields: ["firstName", "lastName"]
                      allowedFields: ["phoneNumber", "otp"]
                      message: "Les champs suivants ne sont pas autorisés: firstName, lastName"

        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Erreur interne du serveur"
                  data:
                    type: object
                    nullable: true

      security: []